/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2020-05-29 11:57:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ucl.ac.uk.main.Shop;

public final class ShopOpeningTimes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ucl.ac.uk.main.Shop");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    Shop shop = (Shop) request.getAttribute("user");

      out.write("\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/meta.jsp", out, false);
      out.write("\n");
      out.write("    <title>Shop Opening Times</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/ShopOpeningTimes.css\">\n");
      out.write("    <script>\n");
      out.write("        document.addEventListener(\"DOMContentLoaded\", function(event){\n");
      out.write("            let days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];\n");
      out.write("            days.forEach(element => ch(element));\n");
      out.write("        })\n");
      out.write("\n");
      out.write("        function ch(c){\n");
      out.write("            var el = document.getElementById(c);\n");
      out.write("            var start = \"startTime\" + c;\n");
      out.write("            var finish = \"finishTime\" + c;\n");
      out.write("            var dash = \"dash\" + c;\n");
      out.write("            if(el.checked){\n");
      out.write("                document.getElementById(start).style.display = 'none';\n");
      out.write("                document.getElementById(finish).style.display = 'none';\n");
      out.write("                document.getElementById(dash).style.display = 'none';\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function checkAction(c){\n");
      out.write("            var day = c.value;\n");
      out.write("            var start = \"startTime\" + day;\n");
      out.write("            var finish = \"finishTime\" + day;\n");
      out.write("            var dash = \"dash\" + day;\n");
      out.write("            var nz = \"Closed\" + day;\n");
      out.write("            if(c.checked){\n");
      out.write("                document.getElementById(start).style.display = 'none';\n");
      out.write("                document.getElementById(finish).style.display = 'none';\n");
      out.write("                document.getElementById(dash).style.display = 'none';\n");
      out.write("            }\n");
      out.write("            else{\n");
      out.write("                document.getElementById(start).style.display = 'inline';\n");
      out.write("                document.getElementById(finish).style.display = 'inline';\n");
      out.write("                document.getElementById(dash).style.display = 'inline';\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<header>\n");
      out.write("    ");
      out.print(shop.getName());
      out.write("\n");
      out.write("</header>\n");
      out.write("<div class=\"menu\">\n");
      out.write("    <a href=\"/ShopHome\" class=\"button button1\">Home</a>\n");
      out.write("    <a href=\"/ShopProducts\" class=\"button button2\">Products</a>\n");
      out.write("    <a href=\"/ShopWorkingTimes\" class=\"button button3\">Opening Times</a>\n");
      out.write("    <a href=\"/ShopDetails\" class=\"button button4\">Details</a>\n");
      out.write("</div>\n");
      out.write("<div class=\"list\">\n");
      out.write("    <form id=\"productForm\" method=\"post\" action=\"/ShopOpeningTimes\">\n");
      out.write("        <input type=\"hidden\" name=\"First\" value=\"1\">\n");
      out.write("        <ul id=\"productList\">\n");
      out.write("            <li> <span>Monday:</span>\n");
      out.write("                <input type=\"time\" id=\"startTimeMonday\" name=\"startTimeMonday\" value=\"");
      out.print(shop.getOpeningTime("Monday"));
      out.write("\">\n");
      out.write("                <pre id=\"dashMonday\"> - </pre>\n");
      out.write("                <input type=\"time\" id=\"finishTimeMonday\" name=\"finishTimeMonday\" value=\"");
      out.print(shop.getClosingTime("Monday"));
      out.write("\">\n");
      out.write("                <input type=\"checkbox\" id=\"Monday\" name=\"closedMonday\" value=\"Monday\"\n");
      out.write("                       ");

                    if(!shop.getIsWorking("Monday")){
                        
      out.write("checked");

                    }
                       
      out.write("\n");
      out.write("                       onchange=\"checkAction(this)\">\n");
      out.write("                <label for=\"Monday\">Closed</label>\n");
      out.write("            </li>\n");
      out.write("            <li> <span>Tuesday:</span>\n");
      out.write("                <input type=\"time\" id=\"startTimeTuesday\" name=\"startTimeTuesday\" value=\"");
      out.print(shop.getOpeningTime("Tuesday"));
      out.write("\">\n");
      out.write("                <pre id=\"dashTuesday\"> - </pre>\n");
      out.write("                <input type=\"time\" id=\"finishTimeTuesday\" name=\"finishTimeTuesday\" value=\"");
      out.print(shop.getClosingTime("Tuesday"));
      out.write("\">\n");
      out.write("                <input type=\"checkbox\" id=\"Tuesday\" name=\"closedTuesday\" value=\"Tuesday\"\n");
      out.write("                       ");

                    if(!shop.getIsWorking("Tuesday")){
                        
      out.write("checked");

                    }
                       
      out.write("\n");
      out.write("                       onchange=\"checkAction(this)\">\n");
      out.write("                <label for=\"Tuesday\">Closed</label>\n");
      out.write("            </li>\n");
      out.write("            <li> <span>Wednesday:</span>\n");
      out.write("                <input type=\"time\" id=\"startTimeWednesday\" name=\"startTimeWednesday\" value=\"");
      out.print(shop.getOpeningTime("Wednesday"));
      out.write("\">\n");
      out.write("                <pre id=\"dashWednesday\"> - </pre>\n");
      out.write("                <input type=\"time\" id=\"finishTimeWednesday\" name=\"finishTimeWednesday\" value=\"");
      out.print(shop.getClosingTime("Wednesday"));
      out.write("\">\n");
      out.write("                <input type=\"checkbox\" id=\"Wednesday\" name=\"closedWednesday\" value=\"Wednesday\"\n");
      out.write("                       ");

                    if(!shop.getIsWorking("Wednesday")){
                        
      out.write("checked");

                    }
                       
      out.write("\n");
      out.write("                       onchange=\"checkAction(this)\">\n");
      out.write("                <label for=\"Wednesday\">Closed</label>\n");
      out.write("            </li>\n");
      out.write("            <li> <span>Thursday:</span>\n");
      out.write("                <input type=\"time\" id=\"startTimeThursday\" name=\"startTimeThursday\" value=\"");
      out.print(shop.getOpeningTime("Thursday"));
      out.write("\">\n");
      out.write("                <pre id=\"dashThursday\"> - </pre>\n");
      out.write("                <input type=\"time\" id=\"finishTimeThursday\" name=\"finishTimeThursday\" value=\"");
      out.print(shop.getClosingTime("Thursday"));
      out.write("\">\n");
      out.write("                <input type=\"checkbox\" id=\"Thursday\" name=\"closedThursday\" value=\"Thursday\"\n");
      out.write("                       ");

                    if(!shop.getIsWorking("Thursday")){
                        
      out.write("checked");

                    }
                       
      out.write("\n");
      out.write("                       onchange=\"checkAction(this)\">\n");
      out.write("                <label for=\"Thursday\">Closed</label>\n");
      out.write("            </li>\n");
      out.write("            <li> <span>Friday:</span>\n");
      out.write("                <input type=\"time\" id=\"startTimeFriday\" name=\"startTimeFriday\" value=\"");
      out.print(shop.getOpeningTime("Friday"));
      out.write("\">\n");
      out.write("                <pre id=\"dashFriday\"> - </pre>\n");
      out.write("                <input type=\"time\" id=\"finishTimeFriday\" name=\"finishTimeFriday\" value=\"");
      out.print(shop.getClosingTime("Friday"));
      out.write("\">\n");
      out.write("                <input type=\"checkbox\" id=\"Friday\" name=\"closedFriday\" value=\"Friday\"\n");
      out.write("                       ");

                    if(!shop.getIsWorking("Friday")){
                        
      out.write("checked");

                    }
                       
      out.write("\n");
      out.write("                       onchange=\"checkAction(this)\">\n");
      out.write("                <label for=\"Friday\">Closed</label>\n");
      out.write("            </li>\n");
      out.write("            <li> <span>Saturday:</span>\n");
      out.write("                <input type=\"time\" id=\"startTimeSaturday\" name=\"startTimeSaturday\" value=\"");
      out.print(shop.getOpeningTime("Saturday"));
      out.write("\">\n");
      out.write("                <pre id=\"dashSaturday\"> - </pre>\n");
      out.write("                <input type=\"time\" id=\"finishTimeSaturday\" name=\"finishTimeSaturday\" value=\"");
      out.print(shop.getClosingTime("Saturday"));
      out.write("\">\n");
      out.write("                <input type=\"checkbox\" id=\"Saturday\" name=\"closedSaturday\" value=\"Saturday\"\n");
      out.write("                       ");

                    if(!shop.getIsWorking("Saturday")){
                        
      out.write("checked");

                    }
                       
      out.write("\n");
      out.write("                       onchange=\"checkAction(this)\">\n");
      out.write("                <label for=\"Saturday\">Closed</label>\n");
      out.write("            </li>\n");
      out.write("            <li> <span>Sunday:</span>\n");
      out.write("                <input type=\"time\" id=\"startTimeSunday\" name=\"startTimeSunday\" value=\"");
      out.print(shop.getOpeningTime("Sunday"));
      out.write("\">\n");
      out.write("                <pre id=\"dashSunday\"> - </pre>\n");
      out.write("                <input type=\"time\" id=\"finishTimeSunday\" name=\"finishTimeSunday\" value=\"");
      out.print(shop.getClosingTime("Sunday"));
      out.write("\">\n");
      out.write("                <input type=\"checkbox\" id=\"Sunday\" name=\"closedSunday\" value=\"Sunday\"\n");
      out.write("                       ");

                    if(!shop.getIsWorking("Sunday")){
                        
      out.write("checked");

                    }
                       
      out.write("\n");
      out.write("                       onchange=\"checkAction(this)\">\n");
      out.write("                <label for=\"Sunday\">Closed</label>\n");
      out.write("            </li>\n");
      out.write("        </ul>\n");
      out.write("    </form>\n");
      out.write("</div>\n");
      out.write("<div class=\"buttons\">\n");
      out.write("    <input class=\"saveButton\" type=\"submit\" form=\"productForm\" value=\"Save\">\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
