/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2020-06-11 17:15:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ucl.ac.uk.main.Model;
import ucl.ac.uk.main.Volunteer;

public final class VolunteerDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ucl.ac.uk.main.Volunteer");
    _jspx_imports_classes.add("ucl.ac.uk.main.Model");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

    Volunteer volunteer = (Volunteer) request.getAttribute("user");
    Model model = (Model) request.getAttribute("model");

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/meta.jsp", out, false);
      out.write("\n");
      out.write("    <title>Volunteer Details</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/VolunteerDetails.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<header>\n");
      out.write("    ");
      out.print(volunteer.getFirstName());
      out.write(' ');
      out.print(volunteer.getLastName());
      out.write("\n");
      out.write("</header>\n");
      out.write("<div class=\"menu\">\n");
      out.write("        <a href=\"VolunteerHome\" class=\"button button1\">Home</a>\n");
      out.write("        <a href=\"VolunteerAvailableRequests\" class=\"button button2\">Available Requests</a>\n");
      out.write("        <a href=\"VolunteerRequests\" class=\"button button3\">My Requests</a>\n");
      out.write("        <a href=\"VolunteerAreas\" class=\"button button4\">Working Areas</a>\n");
      out.write("        <a href=\"VolunteerDetails\" class=\"button button5\">Details</a>\n");
      out.write("</div>\n");
      out.write("<div class=\"list\">\n");
      out.write("    <form id=\"detailsForm\" method=\"post\" class=\"inputForm\" action=\"VolunteerDetails\">\n");
      out.write("        <label for=\"username\">Username:</label>\n");
      out.write("        <input type=\"text\" id=\"username\" name=\"username\" value=\"");
      out.print(volunteer.getUsername());
      out.write("\" required> <br/>\n");
      out.write("        <label for=\"firstName\">First Name:</label>\n");
      out.write("        <input type=\"text\" id=\"firstName\" name=\"firstName\" value=\"");
      out.print(volunteer.getFirstName());
      out.write("\" required> <br/>\n");
      out.write("        <label for=\"lastName\">Last Name:</label>\n");
      out.write("        <input type=\"text\" id=\"lastName\" name=\"lastName\" value=\"");
      out.print(volunteer.getLastName());
      out.write("\" required> <br/>\n");
      out.write("        <label for=\"password\">Password:</label>\n");
      out.write("        <input type=\"password\" id=\"password\" name=\"password\" value=\"");
      out.print(volunteer.getPassword());
      out.write("\" required> <br/>\n");
      out.write("        <label for=\"repeatPassword\">Repeat Password:</label>\n");
      out.write("        <input type=\"password\" id=\"repeatPassword\" name=\"repeatPassword\" value=\"");
      out.print(volunteer.getPassword());
      out.write("\" required> <br/>\n");
      out.write("        <label for=\"address\">Address:</label>\n");
      out.write("        <input type=\"text\" id=\"address\" name=\"address\" value=\"");
      out.print(volunteer.getAddress());
      out.write("\" required> <br/>\n");
      out.write("        <input type=\"text\" id=\"address2\" name=\"address2\"> <br/>\n");
      out.write("        <label for=\"city\">City:</label>\n");
      out.write("        <input type=\"text\" id=\"city\" name=\"city\" value=\"");
      out.print(volunteer.getCity());
      out.write("\" readonly> <br/>\n");
      out.write("        <label for=\"country\">Country:</label>\n");
      out.write("        <input type=\"text\" id=\"country\" name=\"country\" value=\"");
      out.print(volunteer.getCountry());
      out.write("\" readonly> <br/>\n");
      out.write("    </form>\n");
      out.write("</div>\n");
      out.write("<div class=\"buttons\">\n");
      out.write("    <input class=\"saveButton\" type=\"submit\" form=\"detailsForm\" value=\"Save\">\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
