/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2020-06-16 17:37:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import ucl.ac.uk.main.Request;
import ucl.ac.uk.main.Model;
import ucl.ac.uk.main.Vulnerable;
import java.util.Calendar;

public final class VulnerableRequests_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("ucl.ac.uk.main.Vulnerable");
    _jspx_imports_classes.add("ucl.ac.uk.main.Request");
    _jspx_imports_classes.add("ucl.ac.uk.main.Model");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    Vulnerable vulnerable = (Vulnerable) request.getAttribute("user");
    Model model = (Model) request.getAttribute("model");

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/meta.jsp", out, false);
      out.write("\n");
      out.write("    <title>Requests</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/VulnerableRequests.css\">\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        function createNewElement() {\n");
      out.write("            const newLine = document.createElement('li');\n");
      out.write("            newLine.innerHTML = \"<input class='inputProduct' type='text' name='product' placeholder='Product'> <input type='number' name='quantity' placeholder='Quantity'> <input type='number' class='inputDays' name='wait' min='1' max='30' placeholder='Days to wait'><select name='type'><option value='grocery store'>Grocery store</option><option value='pharmacy'>Pharmacy</option></select>\";\n");
      out.write("            document.getElementById(\"productList\").appendChild(newLine);\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<header>\n");
      out.write("    ");
      out.print(vulnerable.getFirstName());
      out.write(' ');
      out.print(vulnerable.getLastName());
      out.write("\n");
      out.write("</header>\n");
      out.write("<div class=\"menu\">\n");
      out.write("    <a href=\"VulnerableHome\" class=\"button button1\">Home</a>\n");
      out.write("    <a href=\"VulnerableRequests\" class=\"button button2\">Requests</a>\n");
      out.write("    <a href=\"VulnerableDetails\" class=\"button button3\">Details</a>\n");
      out.write("</div>\n");
      out.write("<div class=\"list\">\n");
      out.write("    <div class=\"listTitle\">\n");
      out.write("        <div class=\"start\"></div> <div class=\"column\">Product</div><div class=\"column2\">Quantity</div><div class=\"column\">Deliver By</div><div class=\"column\">Accepted</div><div class=\"column\">Type</div>\n");
      out.write("    </div>\n");
      out.write("    <form id=\"productForm\" method=\"post\" action=\"VulnerableRequests\">\n");
      out.write("        <ul id=\"productList\">\n");
      out.write("            ");

                Iterator<Request> iterator = vulnerable.getRequestsIterator();
                int i = 0;
                while(iterator.hasNext()){
                    Request a = iterator.next();
            
      out.write("\n");
      out.write("            <li>\n");
      out.write("                <div class=\"column\">");
      out.print(a.getProduct());
      out.write("</div><div class=\"column2\">");
      out.print(a.getQuantity());
      out.write("</div><div class=\"column\">");
      out.print(a.getDeliverBy().get(Calendar.DATE));
      out.write('-');
      out.print(a.getDeliverBy().get(Calendar.MONTH) + 1);
      out.write('-');
      out.print(a.getDeliverBy().get(Calendar.YEAR));
      out.write("</div>\n");
      out.write("                ");

                    if(a.getIsAccepted()){
                
      out.write("\n");
      out.write("                <div class=\"column\">Yes (");
      out.print(a.getAcceptedBy().getFirstName());
      out.write(' ');
      out.print(a.getAcceptedBy().getLastName());
      out.write(")</div>\n");
      out.write("                ");

                    }else{
                
      out.write("\n");
      out.write("                <div class=\"column\">No</div>\n");
      out.write("                ");
}
      out.write("\n");
      out.write("                <div class=\"column\">");
      out.print(a.getType());
      out.write("</div>\n");
      out.write("                <a href=\"VulnerableRequests?remove=");
      out.print(i);
      out.write("\" class=\"close\"></a></li>\n");
      out.write("            ");

                i++;
                }
            
      out.write("\n");
      out.write("        </ul>\n");
      out.write("    </form>\n");
      out.write("</div>\n");
      out.write("<div class=\"buttons\">\n");
      out.write("    <input class=\"saveButton\" type=\"submit\" form=\"productForm\" value=\"Save\">\n");
      out.write("    <input class=\"newButton\" type=\"button\" value=\"New\" onclick=\"createNewElement()\">\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
